version: '3'

services:
        mysql-development:
                image: mysql:latest
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: test
                volumes:
                        - /var/run/mysqld/:/var/run/mysqld/
                ports:
                        - 3306:3306

        postgres-development:
                image: postgres:latest
                environment:
                        POSTGRES_DB: "test"
                        POSTGRES_USER: "root"
                        POSTGRES_PASSWORD: "root"
                ports:
                        - 5432:5432
                volumes:
                        - /var/run/postgresql/:/var/run/postgresql/